"""add restaurants table"""
from alembic import op
import sqlalchemy as sa


revision = 'f4f4364fc9ad'
down_revision = '0002_customer_email_verification'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'INACTIVE', name='restaurant_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(
    ['manager_id'],
    ['users.id'],
    ondelete='CASCADE',
),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', name='uq_restaurants_manager_id')
    )
    op.create_index('ix_restaurants_status', 'restaurants', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurants_status', table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
