"""add manager restaurant application details"""
from alembic import op
import sqlalchemy as sa


revision = 'fa6b2dec4445'
down_revision = 'f4f4364fc9ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('FSSAI_LICENSE', 'BUSINESS_REGISTRATION', 'GST_CERTIFICATE', 'OWNER_IDENTITY', 'BRANDING_IMAGE', name='restaurant_document_type'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'day_of_week', name='uq_restaurant_hours_day')
    )
    op.add_column('restaurants', sa.Column('cuisine_type', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('pin_code', sa.String(length=10), nullable=True))
    op.add_column('restaurants', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('tables', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'tables')
    op.drop_column('restaurants', 'capacity')
    op.drop_column('restaurants', 'pin_code')
    op.drop_column('restaurants', 'state')
    op.drop_column('restaurants', 'cuisine_type')
    op.drop_table('restaurant_hours')
    op.drop_table('restaurant_documents')
    # ### end Alembic commands ###
